### ISSUE TITLE
Remove default channels

### ISSUE THREAD

**Issue by dvdhngs** [sajjadjaved01/iptv#11]
First of all! Congratulations for this source!! It's unbelievable! much thanks for this!!

Well...I have my own list on a link.m3u
Tried to replace links (simiptv) from my own, but the default channels is showing up again!

Where can I disable default channel e add my own url?

**Comment by sajjadjaved01** [comment]
Thanks 👍
u have to change some code on MainActivity & on Login.
 [un-comment](https://github.com/sajjadjaved01/iptv/blob/master/app/src/main/java/com/muparse/MainActivity.java#L63), [comment](https://github.com/sajjadjaved01/iptv/blob/master/app/src/main/java/com/muparse/MainActivity.java#L63)

**Comment by AlbertEinsteinGlitchPoint** [comment]
i think link is loaded on login correct?

**Comment by AlbertEinsteinGlitchPoint** [comment]
ok i have changed this to load my url list from my xstreams

but still cannot onnect , cannot bypass account login...  say user account not found all the time

can you please tell me if i need to paste on login.java the full m3u list generated from xstreams with get.php/username & pasword?

or do i just need to insert the IP and domain information ?

**Comment by sajjadjaved01** [comment]
@AlbertEinsteinGlitchPoint you just have to put your xStreams Url.
