### ISSUE TITLE
username and password to test

### ISSUE THREAD

**Issue by benza86** [sajjadjaved01/iptv#13]
can you give me username and password to test app

**Comment by sajjadjaved01** [comment]
u have to use set your own server for testing, thanks

**Comment by venky1995** [comment]
Hello javid bro come to WhatsApp. This is Venky!!

**Comment by sajjadjaved01** [comment]
@venky1995 can't bro my mobile is damaged, thats why i'm unable to reply u

**Comment by venky1995** [comment]
Javid bro please come back one important news.. please help me,😥😥 waiting for your reply on whatsapp. I hope your mobile will fix as soon as possible..

**Comment by sajjadjaved01** [comment]
@venky1995 join me on fb/SajjadjavedOfficial 👍

**Comment by AlbertEinsteinGlitchPoint** [comment]
i have xstream server running for testing i have created user and passw login i have downloaded  simple m3u list which contain my user and pass

i loaded this link in the /java login 
public final String urlLink 


but cannot sign in  keeps sayin no account data found..

any help please?

**Comment by sajjadjaved01** [comment]
@AlbertEinsteinGlitchPoint  have to fixed this ???
