### ISSUE TITLE
browse m3u??

### ISSUE THREAD

**Issue by hungvu193** [sajjadjaved01/iptv#14]
i try to run this project and i can't find where the "Browse m3u url" ?
How can i find this?

**Comment by sajjadjaved01** [comment]
explain ...

**Comment by hungvu193** [comment]
can i load playlist from a m3u url?

**Comment by sajjadjaved01** [comment]
not yet first it will download ur m3u list, then display it as list

**Comment by hungvu193** [comment]
so, it's possible?. Can you do a example?

**Comment by sajjadjaved01** [comment]
its possible... but i'm a little busy

**Comment by hungvu193** [comment]
thank you, buddy, so i will close this issue, when you did this feature please reopen it xD
