### ISSUE TITLE
cannot login app 

### ISSUE THREAD

**Issue by AlbertEinsteinGlitchPoint** [sajjadjaved01/iptv#16]
hiya

first of all thanks for the nice app i am trying to test it using my test xstream server

but i cannot connect on it

i have changed the login url information so it can try to load from my xstream test server but its not working

so i have decided to enable debugger to check for errors

and i am getting this on the log when i try to login with user and password i have created on xstream

on menu it shows  account not found and cannot login

and on debugger i see this error

08-12 14:58:52.984 23180-23253/com.muparse E/Google: false
08-12 14:59:00.772 23180-23265/com.muparse E/Google: false
08-12 14:59:09.773 23180-23269/com.muparse E/Google: false
08-12 14:59:34.636 23180-23382/com.muparse E/Google: false

any ideas on how to fix this?

**Comment by AlbertEinsteinGlitchPoint** [comment]
ok so further testing done it looks like its stopping here

Utils.getInstance().Snack(getApplicationContext(), "Account not found.", findViewById(R.id.activity_login));

**Comment by AlbertEinsteinGlitchPoint** [comment]
hi

issue fixed with login everything is working fine

**Comment by sajjadjaved01** [comment]
Nice
