### ISSUE TITLE
EPG support?

### ISSUE THREAD

**Issue by AlbertEinsteinGlitchPoint** [sajjadjaved01/iptv#17]
Hi

is there EPG support? i have seen Logo tvg  but no EPG suport

can this be imported from xstreams?

**Comment by AlbertEinsteinGlitchPoint** [comment]
Hia i have changed the code in order to try push m3u list with m3u_plus option

i tought it woul load the channels icons from xstreams but its not pulling channel icons

can you please point me to the code direction in the m3u parser ?

does it load tv-logo and epg source from the xstreams? or its not implemented yet?

**Comment by sajjadjaved01** [comment]
epg is't implement yet, it loads logo from m3u file, have't checked M3u+.

**Comment by AlbertEinsteinGlitchPoint** [comment]
hiya
thnkxs

i will test it i have added the logo channel on tvg-logo on m3u list file from my middlware

i sent list to xstream also added on xstream the logo list, and with other player i can load logos on app

but with your app logo is not working..
after i login on xstream server i can only see the channel name ordered by alphabetic order..

on other player code they use this code for Epg LOADING external source perhaps you could use same function?

`public class MainActivity
    extends Activity
{
    @Override
    protected void onStart()
    {
        super.onStart();
        
        try {
            Intent intent = new Intent();
            intent.setClassName(_IPTV_CORE_PACKAGE_NAME, _IPTV_CORE_CLASS_NAME);

            // Set your playlist url and uncomment the lines below   
            String playlistUrl = "http://ip-address-of-external-file/get.php?username=user&password=pwd&type=m3u_plus&output=ts";
            intent.setData(Uri.parse(playlistUrl));
            
            // If "package" extra is set, IPTV Core will be able to show your app name as a title
            intent.putExtra("package", getPackageName());
            
            // EPG URL can be set either by "url-tvg" parameter in your playlist or by the following extra (supported since IPTV Core 3.3)
             intent.putExtra("url-tvg", "http://url.site-of-epg.gz");

            startActivity(intent);
            finish();
        } catch (ActivityNotFoundException e) {
            // IPTV core app is not installed, let's ask the user to install it.
            showIptvCoreNotFoundDialog();
        }
    }`



with the  type=m3u_plus&output=ts


i am able to load the specific channel logos and with external URL

**Comment by AlbertEinsteinGlitchPoint** [comment]
Also

its not playing mpeg-ts i have seen this is related to exoplayer, is it possible to change the player on the code?

iptv core player or other working player?

**Comment by sajjadjaved01** [comment]
yes you can implement / use any player you want, but its in you, & exoplayer can play ts link, have to upgrade some exoplayer code.
