### ISSUE TITLE
 how I create and configure server to test the application

### ISSUE THREAD

**Issue by Dahcode** [sajjadjaved01/iptv#20]
please someone help me create my server to test the application I would be grateful thanks in advance

**Comment by sajjadjaved01** [comment]
if you any XtreamCodes server than you can test this. or get an M3U file & place it in assets folder.

**Comment by Dahcode** [comment]
good morning friend, I want to configure the login I could not wait for your help thanks

**Comment by sajjadjaved01** [comment]
Change it base Url in app.
