### ISSUE TITLE
Blank Screen in MainActivity

### ISSUE THREAD

**Issue by ahmetcuneydioglu** [sajjadjaved01/iptv#21]
I can login to the app by entering my username and password but in app I only see a white screen, blank screen only. where can I be making a mistake ?

**Comment by sajjadjaved01** [comment]
Did you replaced the m3u link in MainActivity!

**Comment by ahmetcuneydioglu** [comment]
---MainActivity---
` void loader(String name) {

        try { //new FileInputStream (new File(name)
            is = getAssets().open("Converted.m3u"); // if u r trying to open file from asstes InputStream is = getassets.open(); InputStream
            M3UPlaylist playlist = parser.parseFile(is);
            mAdapter.update(playlist.getPlaylistItems());
        } catch (Exception e) {
            Log.d("Google", "" + e.toString());
        }
    }`


---LoginActivity---

`static final File DEFA = Environment.getExternalStorageDirectory();
    public static final File dir = new File(DEFA.getPath() + "/Netuptv");
    static final File filepath = new File(dir.getPath() + "/Converted.m3u");
    private static Login instance = null;
    public final String urlLink = "http://exampletv.net:8080/get.php?username=myUsername&password=myPassword&type=smart_iptv&output=ts";
    public final String domain = "http://exampletv.net:8080";  //http://portal.example.com:8001";`


i changed only these lines. i can login with myUser and myPass but only showing white screen

**Comment by sajjadjaved01** [comment]
every thing here seems alright
