### ISSUE TITLE
App does load the channels list

### ISSUE THREAD

**Issue by M47H3W** [sajjadjaved01/iptv#23]
It appears that I am having the same issue as #21

In the application, I changed the following line to point to my own xtream server:
`public final String domain = "SERVER URL HERE"; //http://portal.example.com:8001";`

After testing the login, it authenticates my real credentials. It returns "Account not found" for an invalid login which shows that part is working properly.  After providing a correct login, it will authenticate me but it will not load the list of channels. The list is just blank. The server has a lot of channels and I even tested it with another server. They all don't show anything.

**Comment by sajjadjaved01** [comment]
Can you please provide a test line, so i can test.

**Comment by mrhussnain** [comment]
yeah same issue here but shows after scroll up and down

**Comment by murataksu740** [comment]
same issue, scroll up and down not work api level 29

**Comment by Norman191** [comment]
How can i login please ?

**Comment by sajjadjaved01** [comment]
@Norman191 you have to use your own. server url.
