### ISSUE TITLE
The search bar does not work.

### ISSUE THREAD

**Issue by antoniocdz** [sajjadjaved01/iptv#24]
The search bar does not work.
The error is in the playlistadapter.java class in the Filter method, the loop does not work, it displays the blank list.
Part of the source code of the Playadapter.java class, which does not work:

    @Override
    public Filter getFilter () {
        return new Filter () {// TODO search it on github
            @Override
            protected void publishResults (CharSequence constraint, FilterResults results) {
                mItem.clear ();
                //mItem.addAll((ArrayList <M3UItem>) results.values);
                notifyDataSetChanged ();
            }

            @Override
            protected FilterResults performFiltering (CharSequence constraint) {
                FilterResults results = new FilterResults ();
                if (! (constraint.length () == 0)) {
                    mItem.clear ();
                    final String filtePatt = constraint.toString (). toLowerCase (). trim ();
                    for (M3UItem itm: mItem) {
                        if (itm.getItemName (). toLowerCase (). contains (filtePatt)) {
                            Toast.makeText (mContext, "Google", Toast.LENGTH_SHORT) .show ();
                            mItem.add (itm);
                        }
                        mItem.add (itm);
                    }
                }
                results.values ​​= mItem;
                results.count = mItem.size ();
                return results;
            }
        };
    }

How to solve this problem?

**Comment by sajjadjaved01** [comment]
yeah, thats an issue that still exists.
