### ISSUE TITLE
Porting it to android TV OS , using leanback theme

### ISSUE THREAD

**Issue by AlbertEinsteinGlitchPoint** [sajjadjaved01/iptv#25]
Hello

Any plans on implementing TV  android OS TV in the code running on the TV Leanbback Theme menu

**Comment by sajjadjaved01** [comment]
We can, if you want.

**Comment by AlbertEinsteinGlitchPoint** [comment]
I have have Android TV OS 5.1 TV would like to test it..  but cannot run app from native android..

**Comment by sajjadjaved01** [comment]
OKay, will convert it in Leanback them. then check.

**Comment by AlbertEinsteinGlitchPoint** [comment]
Ok thks I will wait for good news for testing when available

**Comment by AlbertEinsteinGlitchPoint** [comment]
Hiya still no support for androidtv OS on latest updates?

**Comment by sajjadjaved01** [comment]
@AlbertEinsteinGlitchPoint i have this in mind, now a days i'm having a busy schedule.
