### ISSUE TITLE
Unable to fetch data

### ISSUE THREAD

**Issue by SezonDev** [sajjadjaved01/iptv#29]
Hello I am trying to configure your application for my IPTV links, for the connection everything is fine but when I display the list of channels I put "Unable Fetch Data"

`val urlLink = "http://iptvpro.vision-new.org"`
`val domain = "http://iptvpro.vision-new.org:8789" //http://portal.example.com:8001";`

**I modify this:**

`CheckNetworkAvailable().execute("$domain/get.php?username=" + email.text + "&password=" + password!!.text + "&type=m3u&output=ts")`

to

`CheckNetworkAvailable().execute("$domain/get.php?username=" + email.text + "&password=" + password!!.text + "&type=m3u_plus&output=mpegts")`

**My android studio log**:
https://hastebin.com/nupofuhafo.properties

Thanks, regards Alex

**Comment by sajjadjaved01** [comment]
@SezonDev also add port into urlLink, then check. 
if their is still any issue, ping me on sajjadjaved01@gmail.com
