### ISSUE TITLE
m3u error when youtube link - Show in Grids not exist

### ISSUE THREAD

**Issue by hadjistyllis** [sajjadjaved01/iptv#4]
Hi sajjad0321
I try using your project with a test m3u, however if a link is youtube (not extension, just end with numbers) list cant load and gives errors. Can you fixed it if possible?

Also I cant find how to make list "Show in Grids" as you mention in readme, seems not exist in code (not a logo decoder as well, can use btw Android-Universal-Image-Loader by nostra13, https://github.com/nostra13/Android-Universal-Image-Loader). 

Thank you for you time.

**Comment by sajjad0321** [comment]
i'll check

**Comment by andysweber** [comment]
My m3u example

#EXTM3U
#EXTINF:-1 tvg-name="Rik1" epg-id=Rik1 tvg-logo=http://www.riknews.com.cy/images/stories/icons/logo-2.png ,RIKSAT
http://l3.cloudskep.com/cybcsat/abr/playlist.m3u8
#EXTINF:-1 tvg-name="ΕΡΤ1" epg-id=EPT1.gr tvg-logo=https://goo.gl/hD0NSD ,ERT1 WorldWide WebTV
https://www.youtube.com/watch?v=Zx98moCvkpU

I get notification error "lenght=65; regionStart=0; regionLength=-1"
If I remove the youtube channels then runs ok and show the channels.

Logcat when youtube link
[https://pastebin.com/raw/LBQkNXaj](url)

Logcat without youtube link
[https://pastebin.com/raw/2V1WDyU9](url)

Logcats seems identical, dont show the error I think.

If you need any farther info message me  :)

**Comment by sajjadjaved01** [comment]
Thanks, for now this reads m3u links i've added ExoPlayer, and as i know exoplyer also can't play direct youtube links.
