### ISSUE TITLE
searchActivity don't exist

### ISSUE THREAD

**Issue by benza86** [sajjadjaved01/iptv#8]
the file searchActivity don't exist
why can I authorise just login and password just i added in  firebase

**Comment by sajjad0321** [comment]
I have to use firebase api, check their documentation

**Comment by benza86** [comment]
you can just search in listview

2018-03-30 14:15 GMT+01:00 sajjad javed <notifications@github.com>:

**Comment by benza86** [comment]
Hello
can you contact me if search in listview  work?
Best regards

2018-03-30 14:33 GMT+01:00 benzarti mejdi <benza1401@gmail.com>:

**Comment by sajjadjaved01** [comment]
@benza86 i have fixed some issues.
